openapi: 3.0.0
info:
  title: 01B - Configurar Factura Electrónica
  version: 1.0.0
servers:
  - url: http://buho.fastura.uio.la/api
    description: Servidor Principal
paths:
  /ubl2.1/config/software:
    put:
      summary: Configurar Software
      description: |
        CONFIGURAR SOFTWARE
        
        - Requiere un token de autorizacion.
        - El campo id, corresponde al id de software que entrega la DIAN.
        - El campo pin, corresponde al pin del software propio.
      tags:
        - Configuración Factura Electrónica
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  example: "82bf0c5e-0117-434d-9471-8a5ee58ae682"
                pin:
                  type: integer
                  example: 12345
      responses:
        '200':
          description: Software configurado con éxito
          content:
            application/json:
              schema:
                type: object
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
