openapi: 3.0.0
info:
  title: 01E - Documentos Equivalentes
  version: 1.0.0
servers:
  - url: http://buho.fastura.uio.la/api
    description: Servidor Principal
paths:
  /ubl2.1/config/softwareeqdocs:
    put:
      summary: Configurar Software Documentos Equivalentes
      description: |
        CONFIGURAR SOFTWARE EQDOCS
        
        - Requiere un token de autorizacion.
      tags:
        - Configuraci√≥n Documentos Equivalentes
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ideqdocs:
                  type: string
                  example: "6edae6bd-3003-492f-bf0b-b23c32f46333"
                pineqdocs:
                  type: integer
                  example: 12345
      responses:
        '200':
          description: Software eqdocs configurado
          content:
            application/json:
              schema:
                type: object
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
