openapi: 3.0.0
info:
  title: 01C - Configurar Nóminas
  version: 1.0.0
servers:
  - url: http://buho.fastura.uio.la/api
    description: Servidor Principal
paths:
  /ubl2.1/config/softwarepayroll:
    put:
      summary: Configurar Software Nómina
      description: |
        CONFIGURAR SOFTWARE NÓMINA
        
        - Requiere un token de autorizacion.
        - El campo idpayroll, corresponde al id de software que entrega la DIAN.
        - El campo pinpayroll, corresponde al pin del software propio de nómina.
      tags:
        - Configuración Nóminas
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                idpayroll:
                  type: string
                  example: "880eafd9-f445-4e0b-a355-92063e1557a4"
                pinpayroll:
                  type: integer
                  example: 12345
      responses:
        '200':
          description: Software de nómina configurado con éxito
          content:
            application/json:
              schema:
                type: object
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
